### ISSUE TITLE
Consider adding PostgreSQL as database option.

### ISSUE THREAD

**Issue by ncareau** [majuansari/docker-phpdev#4]
PostgreSQL is a wildly used database server for web. A few of my clients use it, so it would be awesome if it was included. I believe it would be a great addition since i feel you try to offer multiple option (version, apache/nginx)

**Comment by majuansari** [comment]
Sure will add that soon.

**Comment by majuansari** [comment]
Added pgsql 9.6.

> docker-compose up pg
